[__config__]
oldver = "old_ver.json"
newver = "new_ver.json"

[typomat]
source = "github"
github = "vupdivup/typomat"
use_latest_release = true

[instagram-cli]
source = "github"
github = "supreme-gg-gg/instagram-cli"
use_latest_release = true
